services:
  shurlx:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - BUILD_TYPE=${BUILD_TYPE}
      - MAX_SHORT_CODE_LEN=${MAX_SHORT_CODE_LEN}
      - MAX_REGISTER_ATTEMPTS=${MAX_REGISTER_ATTEMPTS}
      - REQUESTS_PER_MINUTE=${REQUESTS_PER_MINUTE}
      - BASE_URL=${BASE_URL}
    volumes:
      - sqlite_vol:/app/db

volumes:
  sqlite_vol:
