services:
  shurlx:
    build:
      context: .
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - BUILD_TYPE=${BUILD_TYPE}
      - MAX_SHORT_CODE_LEN=${MAX_SHORT_CODE_LEN}
      - MAX_REGISTER_ATTEMPTS=${MAX_REGISTER_ATTEMPTS}
